# -*- coding: utf-8 -*-
"""AI Datascience tutor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYOfdME5ZCmgeAGsy5f2qrJxy1DaGnps
"""

!pip install streamlit langchain langchain-google-genai google-generativeai

# Commented out IPython magic to ensure Python compatibility.
# %%writefile datasci_tutor.py
# import streamlit as st
# from langchain.memory import ConversationBufferMemory
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_core.prompts import ChatPromptTemplate
# from langchain_core.output_parsers import StrOutputParser
# 
# # Load API Key
# with open("/content/code.txt") as f:
#     API_KEY = f.read().strip()
# 
# # Initialize Memory
# if "memory" not in st.session_state:
#     st.session_state.memory = ConversationBufferMemory()
# 
# # Define AI Tutor Prompt
# prompt = ChatPromptTemplate(
#     messages=[
#         (
#             "system",
#             """
#             You are an AI-powered Data Science Tutor.
#             Your job is to help users with data science topics, including:
#             - Machine Learning
#             - Data Analytics
#             - Python for Data Science
#             - Deep Learning
#             - Statistics and Probability
#             - Data Visualization (Matplotlib, Seaborn)
#             - SQL for Data Science
# 
#             Always provide **clear, step-by-step explanations** with examples.
#             If a question is **not related to data science**, politely refuse to answer.
# 
#             Keep responses **short and easy to understand**.
#             """
#         ),
#         ("human", "{question}")
#     ]
# )
# 
# # Initialize AI Model
# chat_model = ChatGoogleGenerativeAI(google_api_key=API_KEY, model="gemini-1.5-flash")
# 
# # Output Parser
# output_parser = StrOutputParser()
# 
# # Processing Chain
# chain = prompt | chat_model | output_parser
# 
# # Function to Get AI Response
# def get_response(question):
#     response = chain.invoke({"question": question})
#     st.session_state.memory.save_context({"question": question}, {"response": response})
#     return response
# 
# # Custom CSS for Attractive UI
# st.markdown(
#     """
#     <style>
#     body {
#         background-image: url('https://source.unsplash.com/1600x900/?technology,ai');
#         background-size: cover;
#         font-family: 'Arial', sans-serif;
#     }
#     .sidebar .sidebar-content {
#         background-color: #1a1a1a !important;
#         color: white !important;
#     }
#     .chat-box {
#         border-radius: 10px;
#         padding: 10px;
#         margin-bottom: 10px;
#     }
#     .user-msg {
#         background-color: #4CAF50;
#         color: white;
#         text-align: right;
#     }
#     .ai-msg {
#         background-color: #009688;
#         color: white;
#     }
#     .chat-container {
#         max-height: 400px;
#         overflow-y: auto;
#         padding: 10px;
#     }
#     .custom-title {
#         font-size: 32px;
#         font-weight: bold;
#         text-align: center;
#         color: #ffcc00;
#         text-shadow: 2px 2px #222;
#     }
#     .dark-mode-toggle {
#         position: fixed;
#         top: 10px;
#         right: 10px;
#         background: black;
#         color: white;
#         padding: 5px 15px;
#         border-radius: 10px;
#         cursor: pointer;
#     }
#     </style>
#     """,
#     unsafe_allow_html=True
# )
# 
# # Sidebar for Chat History
# with st.sidebar:
#     st.image("https://cdn-icons-png.flaticon.com/512/2721/2721291.png", width=100)  # AI Icon
#     st.header("📜 Chat History")
#     if st.session_state.memory.chat_memory.messages:
#         for msg in st.session_state.memory.chat_memory.messages:
#             if msg.type == "human":
#                 st.markdown(f"🧑 **You:** {msg.content}", unsafe_allow_html=True)
#             else:
#                 st.markdown(f"🤖 **AI:** {msg.content}", unsafe_allow_html=True)
#     else:
#         st.write("No chat history yet.")
# 
# # Main Chat UI
# st.markdown("<h1 class='custom-title'>🤖 AI Data Science Tutor</h1>", unsafe_allow_html=True)
# st.subheader("💡 Ask me anything about Data Science!")
# 
# # Chat Container
# st.markdown("<div class='chat-container'>", unsafe_allow_html=True)
# 
# user_question = st.text_area(
#     "Enter your question here:",
#     placeholder="e.g., What is Gradient Descent?",
#     help="Type a data science-related question and get an answer from the AI tutor!"
# )
# 
# # Fetch Answer & Display in Beautiful Style
# if st.button("🚀 Get Answer", use_container_width=True):
#     if user_question:
#         with st.spinner("🤔 Thinking..."):
#             answer = get_response(user_question)
#             st.markdown(f"<div class='chat-box user-msg'>{user_question}</div>", unsafe_allow_html=True)
#             st.markdown(f"<div class='chat-box ai-msg'>{answer}</div>", unsafe_allow_html=True)
#     else:
#         st.warning("⚠ Please enter a question.")
# 
# st.markdown("</div>", unsafe_allow_html=True)
# 
# # Dark Mode Toggle
# st.markdown("<div class='dark-mode-toggle'>🌙 Toggle Dark Mode</div>", unsafe_allow_html=True)
#

!npm install localtunnel
!streamlit run /content/datasci_tutor.py &>/content/logs.txt &
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com