# -*- coding: utf-8 -*-
"""Audio Transcription.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgyBsIx2TaCgiHDUUYhHeXJLdJu8EMbL

**Enhancing Search Engine Relevance for Video Subtitles**
"""

import sqlite3
import zipfile
import io

# Connect to the subtitles database
db_path = r'/content/drive/MyDrive/Copy of eng_subtitles_database.db'
conn = sqlite3.connect(db_path)
cursor = conn.cursor()

# Fetch a single subtitle record
cursor.execute("SELECT num, name, content FROM zipfiles LIMIT 1")
num, name, content = cursor.fetchone()

# Extract .srt from zipped binary
zip_file = zipfile.ZipFile(io.BytesIO(content))
srt_file = zip_file.namelist()[0]  # Assume 1 file per zip
text = zip_file.read(srt_file).decode('utf-8', errors='ignore')

print(f"Subtitle ID: {num}\nFilename: {name}\nText Preview:\n{text[:1000]}")

"""Data preprocessing"""

import re

def clean_subtitle_text(raw_text):
    text = re.sub(r'\d{2}:\d{2}:\d{2},\d{3} --> \d{2}:\d{2}:\d{2},\d{3}', '', raw_text)
    text = re.sub(r'^\d+\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'http\S+|www\S+|osdb\.link\S+', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\s+', ' ', text).strip().lower()
    return text

cleaned_text = clean_subtitle_text(text)
print(cleaned_text[:1000])

"""Chunking"""

def chunk_text(text, chunk_size=50, overlap=10):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = ' '.join(words[i:i + chunk_size])
        if len(chunk.split()) >= 10:
            chunks.append(chunk)
    return chunks

chunks = chunk_text(cleaned_text)
print(f"Chunks: {len(chunks)}\n\nSample:\n{chunks[0]}")

"""Embedding"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
chunk_embeddings = model.encode(chunks, show_progress_bar=True)

"""Installation chromadb"""

import chromadb

# Use the new default in-memory client (sufficient for local/dev)
client = chromadb.Client()

# Create collection
collection = client.get_or_create_collection("subtitle_chunks")

# Add chunks and embeddings
ids = [f"chunk_{i}" for i in range(len(chunks))]

collection.add(
    documents=chunks,
    ids=ids,
    embeddings=chunk_embeddings
)

print("✅ Chunks added to in-memory ChromaDB")

"""Audio Transcription"""

import whisper

# Load Whisper model
whisper_model = whisper.load_model("base")

# Transcribe audio file
result = whisper_model.transcribe(r"/content/Sample audio.m4a")
transcribed_text = result['text']
print("🎧 Transcribed:\n", transcribed_text)

query_cleaned = clean_subtitle_text(transcribed_text)
print("🧹 Cleaned Query:\n", query_cleaned)
query_embedding = model.encode([query_cleaned])[0]

results = collection.query(
    query_embeddings=[query_embedding],
    n_results=5  # Top 5 closest chunks
)

# Display results
print("🔍 Top Matching Subtitle Chunks:\n")
for doc, dist in zip(results['documents'][0], results['distances'][0]):
    print(f"[Score: {1 - dist:.4f}] {doc}\n")

# Create a Streamlit script
script_path = "/content/whisper_transcribe.py"
script_content = """
import streamlit as st
import whisper
import chromadb
from sentence_transformers import SentenceTransformer

st.title("🎙️ Audio Transcription")

# Load Whisper Model
@st.cache_resource
def load_whisper():
    return whisper.load_model("base")

whisper_model = load_whisper()

# Load Sentence Transformer
@st.cache_resource
def load_embedding_model():
    return SentenceTransformer("all-MiniLM-L6-v2")

embedding_model = load_embedding_model()

# Initialize ChromaDB
chroma_client = chromadb.PersistentClient(path="chroma_db")
collection = chroma_client.get_or_create_collection(name="subtitles")

# Sample subtitle chunks (Replace with real data)
subtitles = [
    "The Prophet Muhammad sent letters to rulers inviting them to Islam.",
    "Heraklius was a Byzantine Emperor who received the Prophet’s letter.",
    "The letter to Heraklius spoke about the oneness of God and guidance.",
    "Islamic history contains many diplomatic correspondences.",
    "Studying old letters helps us understand history better."
]

# Store subtitles in ChromaDB with embeddings
for i, subtitle in enumerate(subtitles):
    embedding = embedding_model.encode(subtitle).tolist()
    collection.add(ids=[str(i)], embeddings=[embedding], documents=[subtitle])

# File uploader
uploaded_file = st.file_uploader("Upload an audio file", type=["wav", "mp3", "m4a"])

if uploaded_file is not None:
    with open("temp_audio.m4a", "wb") as f:
        f.write(uploaded_file.getbuffer())

    st.audio(uploaded_file, format='audio/mpeg')

    with st.spinner("Transcribing..."):
        result = whisper_model.transcribe("temp_audio.m4a")
        transcribed_text = result['text']
        st.write("### 🎧 Transcribed Text:")
        st.write(transcribed_text)

        # Generate embedding for transcribed text
        query_embedding = embedding_model.encode([transcribed_text])[0].tolist()

        # Query top 5 matching subtitles
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=5  # Top 5 closest chunks
        )

        st.write("### 🔍 Top Matching Subtitle Chunks:")
        for doc, dist in zip(results['documents'][0], results['distances'][0]):
            st.write(f"**[Score: {1 - dist:.4f}]** {doc}")

"""

# Save the script
with open(script_path, "w") as script_file:
    script_file.write(script_content)

print("✅ app.py created successfully!")

# Run the Streamlit app
!streamlit run /content/whisper_transcribe.py &>/content/logs.txt &

# Expose via localtunnel
!npx localtunnel --port 8501 & curl ipv4.icanhazip.com